---

- name: Setup as-system
  hosts: as_system1
  become: yes
  become_method: sudo
  roles:
    - { role: common, tags: ['common'] }
    - { role: users, tags: ['users'] }
    - { role: sudo, tags: ['sudo'] }
    - { role: sshd, tags: ['sshd'] }
    - { role: unbound, tags: ['unbound'] }
    - { role: certbot, tags: ['certbot'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: grafana, tags: ['grafana'] }
    - { role: prometheus, tags: ['prometheus'] }
    - { role: prometheus_node, tags: ['prometheus_node'] }
    - { role: public_html, tags: ['public_html'] }
    - { role: cockpit, tags: ['cockpit'] }
    - { role: libratbag_doc, tags: ['libratbag_doc'] }
